apiVersion: apps/v1
kind: Deployment 
metadata:
  name: meu-app-python
spec:
  replicas: 4
  selector:
    matchLabels:
      app: meu-app
  template:
    metadata:
      labels:
        app: meu-app
    spec:
      containers:
      - name: python-app
        image: python:3.9-slim
        command: ["/bin/sh", "-c"]
        args: ["echo 'GitOps funcionando com sucesso!' > index.html; python3 -m http.server 8080"]
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: meu-app-service
spec:
  selector:
    app: meu-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP