resources:
  - ../../base

# O "Poder do Admin": Sobrescrevendo apenas o necessário
replicas:
  - name: app-universal
    count: 3

images:
  - name: meu-app
    newName: mateusr1/meu-app
    newTag: v4
