apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-universal
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: app-container
        image: python:3.9-slim
        resources:
          limits:
            cpu: "500m"
            memory: "256Mi"
          requests:
            cpu: "200m"
            memory: "128Mi"
            